### ISSUE TITLE
[EasyErrorHanlder] Add DataCollector (symfony)

### ISSUE THREAD

**Issue by ERuban** [eonx-com/easy-monorepo#585]
Add DataCollector to the `EasyErrorHandler` package to make possible asserting reported data using profiler.

**Comment by BOB41K1987** [comment]
@ERuban @natepage As far as I know, the profiler wouldn't work in console commands and messenger handlers. I'd suggest adding in test environment `InMemoryReporter implements ErrorReporterInterface` the sole purpose of which would be to collect reported exceptions and lets us assert them afterward.

**Comment by natepage** [comment]
@BOB41K1987 it would work but you're right, if the only use case is to assert things in tests, then simply decorate the ErrorHandlerInterface in test environment and add getters to it so you can fetch the errors at a later stage.

**Comment by ERuban** [comment]
@natepage yes, the only use case at this moment is possibility to assert reported exceptions.

**Comment by ERuban** [comment]
So, I've tried to decorate it, and it works in places I want, but seems that ErrorHandler::render() became broken - other tests with the error responses now gets an empty array as a response.
At this moment it looks like:
```
    # services_test.yaml
    EonX\EasyErrorHandler\ErrorHandler:
        arguments:
            $builderProviders: !tagged_iterator \EonX\EasyErrorHandler\Bridge\BridgeConstantsInterface::TAG_ERROR_RESPONSE_BUILDER_PROVIDER
            $reporterProviders: !tagged_iterator \EonX\EasyErrorHandler\Bridge\BridgeConstantsInterface::TAG_ERROR_REPORTER_PROVIDER

    EonX\EasyErrorHandler\Interfaces\ErrorHandlerInterface:
        class: App\Tests\Stub\ErrorHandlerStub
        decorates: EonX\EasyErrorHandler\ErrorHandler
```
(Somehow it doesn't want to work without explicity configured value - `argument "$builderProviders" of method "EonX\EasyErrorHandler\ErrorHandler::__construct()" is type-hinted "iterable", you should configure its value explicitly`)

And the stub-decorator code:
```
final class ErrorHandlerStub implements ErrorHandlerInterface
{
    private ErrorHandlerInterface $decorated;

    private ?Throwable $throwable = null;

    public function __construct(ErrorHandlerInterface $decorated)
    {
        $this->decorated = $decorated;
    }

    public function getReportedException(): ?Throwable
    {
        return $this->throwable;
    }

    public function isVerbose(): bool
    {
        return $this->decorated->isVerbose();
    }

    public function render(Request $request, Throwable $throwable): Response
    {
        return $this->decorated->render($request, $throwable);
    }

    public function report(Throwable $throwable): void
    {
        $this->throwable = $throwable;

        $this->decorated->report($throwable);
    }
}
```

What I'm doing wrong?
